[SQAUSH MERGE] Finished syncing code
commit d1906bfd92ce36e4ca0e08543af87b8e117864dd
Author: Brandon Fong <55638760+BrandonMFong@users.noreply.github.com>
Date:   Mon Mar 23 19:15:09 2020 -0700

    new warning

commit 9b7587a7b4d24950678ea81447f474db7d2803ab
Author: Brandon Fong <55638760+BrandonMFong@users.noreply.github.com>
Date:   Mon Mar 23 19:11:56 2020 -0700

    Tidy up

commit 227982e99353d38c1e91851becdfb439dd4c9c52
Author: Brandon Fong <55638760+BrandonMFong@users.noreply.github.com>
Date:   Mon Mar 23 18:55:38 2020 -0700

    wrong enum again for led

commit 017a1d370ea16fa9c046677b2aabd367a571bec6
Author: Brandon Fong <55638760+BrandonMFong@users.noreply.github.com>
Date:   Mon Mar 23 18:51:07 2020 -0700

    Wrong enum

commit 3f819ffaef0659df59b4670c3d40400f35ac6259
Author: Brandon Fong <55638760+BrandonMFong@users.noreply.github.com>
Date:   Mon Mar 23 18:47:37 2020 -0700

    BOARD -> BCM

commit 59cb8f5fbb0f4fff8970ad76a05932827a7a87fe
Author: Brandon Fong <55638760+BrandonMFong@users.noreply.github.com>
Date:   Mon Mar 23 18:46:01 2020 -0700

    BOARD -> BCM
    [https://stackoverflow.com/questions/20456905/python-raspberry-pi-gpio-error]

commit 1272c46869e8ef9770203fa8b74209921e01b260
Author: Brandon Fong <55638760+BrandonMFong@users.noreply.github.com>
Date:   Mon Mar 23 18:44:08 2020 -0700

    Setting, might have gotten confused with this

commit a13f5143c6cbf45eab253af016fa15de549f6d5e
Author: Brandon Fong <55638760+BrandonMFong@users.noreply.github.com>
Date:   Mon Mar 23 18:39:23 2020 -0700

    Change Infra pin from 8 -> 40

commit 4f540956dd46ab0568496b308cf1f2ab54c40434
Author: Brandon Fong <55638760+BrandonMFong@users.noreply.github.com>
Date:   Mon Mar 23 18:09:35 2020 -0700

    Removing all IO refs

commit 8fcd1437e81e777d4d3ad3762d525ee37e3af90a
Author: Brandon Fong <55638760+BrandonMFong@users.noreply.github.com>
Date:   Mon Mar 23 18:07:25 2020 -0700

    Setting ads to global var

commit b7152ecb3b155271db5225a16a1293d6a457791a
Author: Brandon Fong <55638760+BrandonMFong@users.noreply.github.com>
Date:   Mon Mar 23 18:03:49 2020 -0700

    IO is not referenced in the Maxpower_classes method.

    Note: Remving setup() from IO.py worked.  Code is running.
    Debugging rest

commit 8aba71732e4633892986648e7ffaae6b439dcfd0
Author: Brandon Fong <55638760+BrandonMFong@users.noreply.github.com>
Date:   Mon Mar 23 18:01:52 2020 -0700

    ignore setup()

commit bcc07fb8ac71570ab5b7820a6e88534b4fafd009
Merge: 96a5aca 4d20806
Author: BrandonMFong <fong.m.brandon97@gmail.com>
Date:   Tue Mar 24 00:57:16 2020 +0000

    Merge branch 'Features/MaxPower/bf-SynchronizeCode' of https://github.com/Dual-Power-Generation/DualPowerGeneration into Features/MaxPower/bf-SynchronizeCode

commit 96a5aca651ac1a402a1849ffd9d7f27bdbc94aac
Author: BrandonMFong <fong.m.brandon97@gmail.com>
Date:   Tue Mar 24 00:56:58 2020 +0000

    Resolve merge conflicts

commit 4d2080661385cc33ae7211f8e11e657f9e3fe64e
Author: Brandon Fong <55638760+BrandonMFong@users.noreply.github.com>
Date:   Wed Mar 18 19:53:28 2020 -0700

    [ValueError came back]

    Traceback (most recent call last):
      File "Main.py", line 22, in <module>
        IO.RPI_Handler.init(IO.RPI_Handler);
      File "/home/brandonmfong/SOURCES/Repo/DualPowerGeneration/MaxPowerTracker/MaxPower/IO.py", line 57, in init
        GPIO.setmode(GPIO.BOARD);
    ValueError: A different mode has already been set!

commit 73fd76be51a2ce433b77146013c13480d000ac82
Author: BrandonMFong <fong.m.brandon97@gmail.com>
Date:   Thu Mar 19 02:34:40 2020 +0000

    Removing .pyc files

commit c5143c2b6802578fb7da9ed12d7d2522c3137319
Merge: 6060eda 91610b3
Author: Brandon Fong <55638760+BrandonMFong@users.noreply.github.com>
Date:   Wed Mar 18 19:03:15 2020 -0700

    Merge branch 'master' into Features/MaxPower/bf-SynchronizeCode

commit 6060edaef2fd0729126b499a1c94daff8ed645b6
Author: BrandonMFong <fong.m.brandon97@gmail.com>
Date:   Thu Mar 19 01:55:07 2020 +0000

    Works with this folder from adafruit